Pleno 2022-07-07: Asistencias/votaciones
openpolitica/congreso-pleno-asistencia-votacion pull request #1334
Opened 2022-07-31 09:25 UTC by jeqo

2022-08-04 17:23 UTC, jeqo commented on data/2021-2026/2022/07/07/2022-07-07T12-05-asistencia/resultados.csv
> +presentes,108
En el PDF figura 107

```suggestion
presentes,107
```

2022-08-04 17:26 UTC, jeqo commented on data/2021-2026/2022/07/07/2022-07-08T01-06-votacion/votaciones.csv
> +FP,"VENTURA ANGEL, HÉCTOR JOSÉ",SI
El nombre del congresista esta incorrecto

2022-08-04 17:26 UTC, jeqo commented on data/2021-2026/2022/07/07/2022-07-08T01-06-votacion/votaciones.csv
> +PP,"ZEA CHOQUECHAMBI, OSCAR",NO
```suggestion
PP,"ZEA CHOQUECHAMBIABC, OSCAR",NO
```

2022-08-04 17:30 UTC, jeqo commented on data/2021-2026/2022/07/07/2022-07-07T21-48-votacion/etiquetas.csv
> +etiqueta,valor
```suggestion
etiqueta,valor
proyectos_ley,"74,773,1280,1309"
```

2022-09-15 12:24 UTC, xiooooo approved these changes

2022-09-15 12:24 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados.csv
> +sin_responder,1
El número es 2 en el PDF.

2022-09-15 12:24 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados.csv
> +si,101
El número es 100 en el PDF

2022-09-15 12:24 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados_grupo.csv
> +PP,5,4,0,0,0,1,0,0
3 votaron por Sí en el PDF.

2022-09-15 12:26 UTC, xiooooo requested changes

2022-09-15 12:26 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados.csv
> +si,101
El número es 100 en el PDF

2022-09-15 12:26 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados.csv
> +sin_responder,1
El número es 2 en el PDF.

2022-09-15 12:26 UTC, xiooooo commented on data/2021-2026/2022/07/07/2022-07-07T22-27-votacion/resultados_grupo.csv
> +PP,5,4,0,0,0,1,0,0
3 votaron por Sí en el PDF.

2022-09-25 08:09 UTC, jeqo commented
gracias @xiooooo ! habia un error en las votaciones al contar los presidentes como SI en vez de SIN_RESPUESTA. Ahora los calculos deberian estar corregidos. Confirmas la aprobacion. Gracias!

2023-04-10 04:05 UTC, polobeyk requested changes
Revisar los 6 cambios propuestos, por favor.

2023-04-10 06:20 UTC, polobeyk approved these changes
Pleno listo para aprobar, aunque los dos últimos files no son parte del PDF.

2023-04-10 07:10 UTC, merged