Pleno: 2022-06-02:Asistencias y votaciones de la sesión del 02-06-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1356
Opened 2022-09-25 10:36 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2021-2022 | Titulo: Asistencias y votaciones de la sesión del 02-06-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/19EA839126FB30640525885D006F8F80/$FILE/Asis_vot_OFICIAL_02-06-22.pdf> | Paginas: 41

2023-03-15 19:44 UTC, polobeyk requested changes
Solo corregir los cambios que he propuesto y, luego, aprobar el pleno.

2023-03-15 19:44 UTC, polobeyk commented on data/2021-2026/2022/06/02/2022-06-03T00-02-votacion/metadatos.csv
> +asunto,"TEXTO SUSTITUTORIO DEL PROYECTO DE LEY 412, QUE PROPONE ESTABLECER MEDIDAS ESPECIALES PARA EMPRESAS EN REESTRUCTURACIÓN PATRIMONIAL EN EL MARCO DE LA LEY GENERAL DEL SISTEMA CONCURSAL A FIN D
```suggestion
asunto,"TEXTO SUSTITUTORIO DEL PROYECTO DE LEY 412, QUE PROPONE ESTABLECER MEDIDAS ESPECIALES PARA EMPRESAS EN REESTRUCTURACIÓN PATRIMONIAL EN EL MARCO DE LA LEY GENERAL DEL SISTEMA CONCURSAL A FIN DE FORTALECER LA GESTIÓN AMBIENTAL EN ÁREAS IMPACTADAS Y/O CON PASIVOS AMBIENTALES MINEROS"
```

2023-03-15 19:44 UTC, polobeyk commented on data/2021-2026/2022/06/02/2022-06-03T00-02-votacion/votaciones.csv
> +AP,"ACUÑA PERALTA, MARÍA GRIMANEZA",SI
```suggestion
APP,"ACUÑA PERALTA, MARÍA GRIMANEZA",SI
```

2023-03-15 19:44 UTC, polobeyk commented on data/2021-2026/2022/06/02/2022-06-03T00-02-votacion/resultados_grupo.csv
> +APP,13,7,0,2,2,2,0,0
```suggestion
APP,14,8,0,2,2,2,0,0
```

2023-03-15 19:44 UTC, polobeyk commented on data/2021-2026/2022/06/02/2022-06-03T00-02-votacion/resultados_grupo.csv
> +AP,16,13,0,0,0,2,1,0
```suggestion
AP,15,12,0,0,0,2,1,0
```

2023-03-15 21:01 UTC, jeqo commented
gracias @polobeyk ! ya aplique las correciones, me confirmas si todo se ve bien.

2023-03-29 15:39 UTC, polobeyk requested changes

2023-03-29 20:40 UTC, jeqo commented
Gracias @polobeyk ! Buena captura, puedes revisar las correcciones

2023-03-29 21:28 UTC, polobeyk approved these changes
Todo en orden @jeqo. Pleno listo para aprobar.

2023-04-09 17:01 UTC, merged