Pleno: 2022-06-09:Asistencias y votaciones de la sesión del 09-06-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1358
Opened 2022-09-25 20:05 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2021-2022 | Titulo: Asistencias y votaciones de la sesión del 09-06-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/ACA6624356390AF605258862006BAE8B/$FILE/Asis_vot_OFICIAL_09-06-22.pdf> | Paginas: 45

2023-03-09 16:55 UTC, ACARRERAGARCIA requested changes

2023-03-09 17:13 UTC, ACARRERAGARCIA requested changes

2023-03-09 17:13 UTC, ACARRERAGARCIA commented on data/2021-2026/2022/06/09/2022-06-09T13-24-votacion/resultados.csv
> +numero_legal,129
130

2023-03-09 17:13 UTC, ACARRERAGARCIA commented on data/2021-2026/2022/06/09/2022-06-09T13-24-votacion/resultados.csv
> +sin_responder,3
4

2023-03-17 20:21 UTC, ACARRERAGARCIA requested changes

2023-03-24 20:50 UTC, ACARRERAGARCIA commented on data/2021-2026/2022/06/09/2022-06-09T17-31-votacion/resultados.csv
Jorge, los 3 ajustes aparecen como resueltos pero; por ejemplo, sigue apareciendo "129", donde debería ser 130 :(

2023-03-24 20:51 UTC, ACARRERAGARCIA commented on data/2021-2026/2022/06/09/2022-06-09T17-31-votacion/resultados.csv
Jorge, los 3 ajustes aparecen como resueltos pero; por ejemplo, sigue apareciendo "129", donde debería ser 130 :(

2023-03-24 21:50 UTC, jeqo commented on data/2021-2026/2022/06/09/2022-06-09T17-31-votacion/resultados.csv
disculpa ale! espero ahora este correcto

2023-03-27 17:39 UTC, ACARRERAGARCIA approved these changes

2023-03-27 18:24 UTC, merged