Pleno: 2022-05-04:Asistencias y votaciones de la sesión del 04-05-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1384
Opened 2022-10-18 08:24 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2021-2022 | Titulo: Asistencias y votaciones de la sesión del 04-05-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/8471CF41214854640525883F00502057/$FILE/Asis_vot_OFICIAL_04-05-22.pdf> | Paginas: 28

2022-11-10 11:53 UTC, xiooooo requested changes

2022-11-10 11:53 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T17-19-votacion/resultados.csv
> +sin_responder,0
No está de acuerdo a la ficha.

2022-11-10 11:53 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T17-23-votacion/resultados.csv
> +sin_responder,3
No está de acuerdo a la ficha.

2022-11-10 11:53 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T17-27-votacion/resultados.csv
> +sin_responder,2
No está de acuerdo a la ficha.

2022-11-10 11:53 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T17-32-votacion/resultados.csv
> +sin_responder,3
No está de acuerdo a la ficha.

2022-11-16 11:32 UTC, jeqo commented
Gracias @xiooooo ! ahora estoy comenzando a revisar este pleno

2022-11-16 12:09 UTC, jeqo commented
@xiooooo he regenerado las votaciones, podrias darle otra chequeada?

2022-11-17 01:21 UTC, xiooooo requested changes

2022-11-17 01:21 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T18-36-votacion/resultados_grupo.csv
> +APP,14,12,1,0,0,1,0,0
Corroborar información

2022-11-17 11:38 UTC, xiooooo requested changes

2022-11-17 11:38 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T22-25-votacion/resultados.csv
> +sin_responder,9
No está de acuerdo a la ficha

2022-11-17 11:38 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T22-25-votacion/resultados_grupo.csv
> +FP,23,17,0,0,3,2,1,0
No está de acuerdo a la ficha

2022-11-17 11:38 UTC, xiooooo commented on data/2021-2026/2022/05/04/2022-05-04T22-25-votacion/resultados_grupo.csv
> +PL,32,25,0,1,1,2,3,0
No está de acuerdo a la ficha

2022-11-18 14:30 UTC, jeqo commented
Gracias xio! Ya estoy regristrando los congresistas faltantes en log.txt. Si le puedes dar una revision adicional, gracias!

2023-03-14 03:09 UTC, polobeyk approved these changes

2023-03-14 03:11 UTC, polobeyk approved these changes

2023-03-14 21:03 UTC, merged