Pleno: 2022-05-11:Asistencias y votaciones de la sesión del 11-05-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1386
Opened 2022-10-18 08:34 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2021-2022 | Titulo: Asistencias y votaciones de la sesión del 11-05-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/C2A60BCB0DEF41F405258844006AAA14/$FILE/Asis_vot_OFICIAL_11-05-22.pdf> | Paginas: 5

2022-11-24 10:45 UTC, xiooooo requested changes

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T17-01-votacion/resultados.csv
> +sin_responder,3
No está acorde al documento

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T17-01-votacion/resultados_grupo.csv
> +AP,15,13,0,0,0,2,0,0
No está de acuerdo al documento

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T17-01-votacion/resultados_grupo.csv
> +APP,13,12,0,0,0,1,0,0
No está de acuerdo al documento

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T18-45-votacion/resultados.csv
> +sin_responder,32
No está de acuerdo al documento.

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T18-45-votacion/resultados_grupo.csv
> +AP,15,11,0,0,4,0,0,0
No está de acuerdo al documento.

2022-11-24 10:45 UTC, xiooooo commented on data/2021-2026/2022/05/11/2022-05-11T18-45-votacion/resultados_grupo.csv
> +APP,13,9,0,0,4,0,0,0
No está de acuerdo al documento.

2023-03-09 16:46 UTC, ACARRERAGARCIA approved these changes

2023-03-09 20:44 UTC, merged