Pleno: 2022-05-04:Asistencias y votaciones de la sesión del 04-05-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1423
Opened 2023-03-15 22:42 UTC by jeqo

2023-03-15 22:44 UTC, jeqo commented
@polobeyk podrias revisar este PR porfa? es similar a #1384, pero tuve que revertirlo por unos problemas de codigo.

2023-03-22 01:16 UTC, polobeyk requested changes
@jeqo Por favor, revisa los 6 cambios que he propuesto.

2023-03-22 01:16 UTC, polobeyk commented on data/2021-2026/2022/05/04/grupo_parlamentario.csv
> +CD,CAMBIO DEMOCRÁTICO
Este grupo parlamentario (CD, CAMBIO DEMOCRÁTICO) no es parte de este Pleno. Hay que eliminarlo.

2023-03-22 21:00 UTC, jeqo commented on data/2021-2026/2022/05/04/grupo_parlamentario.csv
> +CD,CAMBIO DEMOCRÁTICO
Si esta en las primeras asistencias/votaciones. Cambia al final. Chequea el PDF para confirmar

2023-03-24 18:53 UTC, polobeyk approved these changes
Todo en orden. Pleno listo para aprobar.

2023-03-24 21:07 UTC, merged