Pleno: 2022-12-21:Asistencias y votaciones de la sesión del 21-12-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1450
Opened 2023-04-10 06:19 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2022-2023 | Titulo: Asistencias y votaciones de la sesión del 21-12-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/C97DDE166DA61F5B05258925006D93D5/$FILE/Asis_vot_OFICIAL_21-12-2022.pdf> | Paginas: 41

2023-06-22 03:35 UTC, polobeyk commented
@jeqo Falta la página 20: la votación de las 20:01

2023-06-22 07:11 UTC, polobeyk requested changes

2023-06-22 07:11 UTC, polobeyk commented on data/2021-2026/2022/12/21/2022-12-21T23-49-asistencia/notas.csv
> +hora,nota
```suggestion
hora,nota
23:49,"El presidente del Congreso deja constancia de la asistencia de los congresistas Cutica Ccama, Paredes Fonseca, López Morales, Sánchez Palomino y Revilla Villanueva."
```

2023-06-22 07:11 UTC, polobeyk commented on data/2021-2026/2022/12/21/2022-12-21T23-55-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
23:55,"El presidente del Congreso deja constancia del voto a favor de los congresistas Revilla Villanueva, López Morales, Paredes Fonseca, Medina Hermosilla, Torres Salinas, Sánchez Palomino, Montalvo Cubas y Zeta Chunga; del voto en contra de los congresistas Taipe Coronado y Pablo Medina; del voto en abstención de los congresistas Cutica Ccama y Cruz Mamani; y del cambio de voto de a favor por voto en contra del congresista Kamiche Morante y de voto en contra por voto a favor del congresista Ventura Angel."
```

2023-06-26 14:43 UTC, jeqo commented
@polobeyk gracias! ya encontre el error y subi la votacion faltante.

2023-06-29 19:03 UTC, polobeyk commented
@jeqo , A la votación de las 20:01 le falta el archivo de notas. Agrégalo, porfa. Luego, inserto la nota correspondiente.

2023-06-29 19:12 UTC, polobeyk reviewed
@jeqo , A la votación de las 20:01 le falta el archivo de notas. Agrégalo, porfa. Luego, inserto la nota correspondiente.

2023-06-30 00:27 UTC, polobeyk reviewed
Se borraron todas las notas anteriores =(

2023-06-30 00:27 UTC, polobeyk commented on data/2021-2026/2022/12/21/2022-12-21T20-01-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
20:01,"El presidente del Congreso deja constancia del voto a favor de los congresistas Bálcazar Zelada, Anderson Ramírez, Martínez Talavera, Montalvo Cubas, Elías Avalos, Huamán Coronado, Cordero Jon Tay Luis y Córdova Lobatón; del voto en contra de los congresistas Bazán Narro, Luque Ibarra y Sánchez Palomino; y del voto en abstención del congresista Kamiche Morante."
```

2023-07-04 05:45 UTC, polobeyk approved these changes

2023-07-04 05:46 UTC, merged