Pleno: 2022-12-07:Asistencia y votación de la sesión del 07-12-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1451
Opened 2023-04-10 06:20 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2022-2023 | Titulo: Asistencia y votación de la sesión del 07-12-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/91E5970F99BA235C05258917006DF112/$FILE/Asis_vot_OFICIAL_07-12-2022.pdf> | Paginas: 2

2023-04-10 20:06 UTC, jeqo commented
@polobeyk al parecer estaba con formato antiguo. ya subi los cambios manualmente.

2023-06-01 04:58 UTC, polobeyk requested changes

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/votaciones.csv
> +PL,"BELLIDO UGARTE, GUIDO",ABSTENCION
```suggestion
NA,"BELLIDO UGARTE, GUIDO",ABSTENCION
```

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/resultados_grupo.csv
> +NA,5,4,0,0,0,0,0,1
```suggestion
NA,8,6,0,1,0,0,0,1
```

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/votaciones.csv
> +PP,"BURGOS OLIVEROS, JUAN BARTOLOMÉ",SI
```suggestion
NA,"BURGOS OLIVEROS, JUAN BARTOLOMÉ",SI
```

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/resultados_grupo.csv
> +PP,6,6,0,0,0,0,0,0
```suggestion
PP,5,5,0,0,0,0,0,0
```

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/votaciones.csv
> +PD,"VALER PINTO, HÉCTOR",SI
```suggestion
NA,"VALER PINTO, HÉCTOR",SI
```

2023-06-01 04:58 UTC, polobeyk commented on data/2021-2026/2022/12/07/2022-12-07T13-16-votacion/resultados_grupo.csv
> +PD,6,2,1,0,2,0,1,0
```suggestion
PD,5,1,1,0,2,0,1,0
```

2023-06-15 21:44 UTC, jeqo commented
@polobeyk creo que subi mal los cambios 😂 , he creado un nuevo PR: #1502

2023-06-15 21:44 UTC, closed without merging