Pleno: 2022-12-28:Asistencias y votaciones de la sesión del 28-12-2022
openpolitica/congreso-pleno-asistencia-votacion pull request #1453
Opened 2023-04-10 19:22 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2022-2023 | Titulo: Asistencias y votaciones de la sesión del 28-12-2022 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/070E8D09AB9201F90525892E0074265B/$FILE/Asis_vot_OFICIAL_28-12-22.pdf> | Paginas: 82

2023-05-02 22:02 UTC, ValeriaRodriguezDaviran reviewed
falta los datos de la ultima hoja del pdf del congreso (pagina 82)

2023-05-04 19:44 UTC, jeqo commented on data/2021-2026/2022/12/28/2022-12-28T17-19-votacion/resultados.csv
> +ausentes,20
Estoy ajustando los datos de esta fecha/hora segun los comentarios en el PDF: 
![image](https://user-images.githubusercontent.com/6180701/236313108-74bb4675-a1b5-4f3d-8b34-75322054eeee.png)

2023-08-18 22:09 UTC, polobeyk requested changes

2023-09-21 02:16 UTC, polobeyk requested changes
Solo volver a ver las notas de la votación de las 17:19

2023-09-28 17:24 UTC, polobeyk approved these changes

2023-09-28 17:24 UTC, merged