Pleno: 2023-01-26:Asistencias y votaciones de la sesión del 26-01-2023
openpolitica/congreso-pleno-asistencia-votacion pull request #1467
Opened 2023-04-15 22:55 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2022-2023 | Titulo: Asistencias y votaciones de la sesión del 26-01-2023 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/9FB08842E670EE28052589470054B87E/$FILE/Asis_vot_OFICIAL_26-01-23.pdf> | Paginas: 25

2023-07-11 03:42 UTC, polobeyk commented
@jeqo ¿Podrías volver a resubir este pleno? En todas las páginas falta el quorum y el conteo del presidente de la mesa. Me avisas, porfa.

2023-07-11 21:31 UTC, jeqo commented
@polobeyk , los quorums ya estan corregidos. Estas votaciones tienen 129 congresistas

2023-09-27 00:35 UTC, polobeyk requested changes
Solo agregar las notas

2023-09-27 00:35 UTC, polobeyk commented on data/2021-2026/2023/01/26/2023-01-26T13-24-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
13:24,"El presidente del Congreso deja constancia del voto a favor del congresista Pazo Nunura."
```

2023-09-27 00:35 UTC, polobeyk commented on data/2021-2026/2023/01/26/2023-01-26T13-27-asistencia/notas.csv
> +hora,nota
```suggestion
hora,nota
13:27"El presidente del Congreso deja constancia de la asistencia del congresista Pazo Nunura."
```

2023-09-27 00:35 UTC, polobeyk commented on data/2021-2026/2023/01/26/2023-01-26T13-29-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
13:29,"El presidente del Congreso deja constancia del voto en contra de los congresistas Pazo Nunura y Burgos Oliveros."
```

2023-09-27 00:35 UTC, polobeyk commented on data/2021-2026/2023/01/26/2023-01-26T16-20-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
16:20,"El presidente del Congreso deja constancia del voto a favor de la congresista Alcarraz Agüero."
```

2023-09-27 00:35 UTC, polobeyk commented on data/2021-2026/2023/01/26/2023-01-26T16-44-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
16:44,"El presidente del Congreso deja constancia del voto a favor del congresista López Ureña."
```

2023-09-28 20:11 UTC, polobeyk approved these changes

2023-09-29 11:34 UTC, merged