Pleno: 2023-12-13:Asistencias y votaciones de la sesión del 13-12-2023
openpolitica/congreso-pleno-asistencia-votacion pull request #1625
Opened 2024-01-08 03:18 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2023-2024 | Titulo: Asistencias y votaciones de la sesión del 13-12-2023 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/B0F3712F5AEA5F6D05258A8500009F2A/$FILE/Asis_y_vot_OFICIAL_de_la_sesión_del_13-12-2023.pdf> | Paginas: 33

2024-02-07 14:57 UTC, DiegoAlmenara requested changes
Estimado Jorge @jeqo ,

En el presente pleno los cambios importantes se encuentran en las siguientes carpetas:
- Votación 21:47

Aparte de esos cambios, agregué datos en los archivos "notas.csv" que lo requerían y corregí cuestiones ortográficas en archivos "metadatos.csv".

Finalmente, aquí se repite el caso del congresista Herrera Mamani/Rospigliosi Capurro que te comenté en mi última revisión.

Saludos cordiales.
Diego.

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
21:47,"El congresista Soto Reyes, presidente del Congreso, deja constancia del voto a favor de los congresistas Palacios Huamán, Juárez Gallegos, Infantes Castañeda, Cerrón Rojas, Taipe Coronado y Ramírez García; y del voto en contra del congresista Sánchez Palomino."
```

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/resultados.csv
> +si,76
```suggestion
si,75
```

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/resultados.csv
> +no,23
```suggestion
no,24
```

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/resultados_grupo.csv
> +TOTAL,130,76,23,3,6,16,5,1
```suggestion
TOTAL,130,75,24,3,6,16,5,1
```

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/resultados_grupo.csv
> +AP,7,4,1,0,0,1,1,0
```suggestion
AP,7,3,2,0,0,1,1,0
```

2024-02-07 14:57 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/13/2023-12-13T21-47-votacion/votaciones.csv
> +AP,"ESPINOZA VARGAS, JHAEC DARWIN",SI
```suggestion
AP,"ESPINOZA VARGAS, JHAEC DARWIN",NO
```

2024-02-20 15:00 UTC, DiegoAlmenara requested changes
Estimado @jeqo ,

En el presente pleno falta resolver/actualizar los cambios solicitados desde "Votación 18:39" en adelante.

Saludos.
Diego

2024-04-02 20:30 UTC, jeqo commented
@DiegoAlmenara por favor revisar nuevamente, gracias.

2024-04-03 20:16 UTC, DiegoAlmenara approved these changes

2024-04-03 22:10 UTC, merged