Pleno: 2023-12-15:Asistencias y votciones de la sesión del 15-12-2023
openpolitica/congreso-pleno-asistencia-votacion pull request #1627
Opened 2024-01-08 04:40 UTC by jeqo

Periodo parlamentario: 2021-2026 | Periodo anual: 2023-2024 | Titulo: Asistencias y votciones de la sesión del 15-12-2023 | URL: <https://www2.congreso.gob.pe/Sicr/RelatAgenda/PlenoComiPerm20112016.nsf/Apleno/6AFE9B1AE22DFFAD05258A86005FF526/$FILE/Asis_y_vot_OFICIAL_de_la_seión_del_15-12-2023.pdf> | Paginas: 25

2024-02-07 22:36 UTC, DiegoAlmenara requested changes
Estimado Jorge @jeqo ,

En el presente pleno los cambios importantes se encuentran en las siguientes carpetas:
- Votación 16:11

Aparte de esos cambios, **agregué datos en los archivos "notas.csv" que lo requerían** y corregí cuestiones ortográficas en archivos "metadatos.csv".

Por otro lado, te comento que **no existe carpeta para la página 11** del PDF (Votación 11:43).

Finalmente, aquí **se repite el caso del congresista Herrera Mamani/Rospigliosi Capurro** que te comenté en mi última revisión.

Saludos cordiales.
Diego.

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-08-asistencia/notas.csv
> +hora,nota
```suggestion
hora,nota
16:08,"El congresista Soto Reyes, presidente del Congreso, deja constancia de la asistencia de la congresista Jáuregui Martínez de Aguayo."
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/metadatos.csv
> +asunto,"RECONSIDERACIÓN DE LA VOTACIÓN POR LA QUE NO SE ALCANZÓ EL NÚMERO DE VOTOS REQUERIDOS PARA LA ADMISIÓN A DEBATE DE LA MOCION DE ORDEN DEL DÍA 9428, QUE PROPONE QUE EL CONGRESO DE LA REPUBLICA
```suggestion
asunto,"RECONSIDERACIÓN DE LA VOTACIÓN POR LA QUE NO SE ALCANZÓ EL NÚMERO DE VOTOS REQUERIDOS PARA LA ADMISIÓN A DEBATE DE LA MOCION DE ORDEN DEL DÍA 9428, QUE PROPONE QUE EL CONGRESO DE LA REPÚBLICA ACUERDE QUE LA COMISIÓN DE JUSTICIA Y DERECHOS HUMANOS EN EL PLAZO DE 10 DÍAS HÁBILES REALICE UNA INVESTIGACIÓN CONTRA LOS MIEMBROS DE LA JUNTA NACIONAL DE JUSTICIA POR CAUSA GRAVE, EN LOS TÉRMINOS DEL ARTÍCULO 157 DE LA CONSTITUCIÓN POLÍTICA DEL PERU Y DEL ARTÍCULO 15, IN FINE, DE LA LEY ORGÁNICA DE LA JUNTA NACIONAL DE JUSTICIA"
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
16:11,"El congresista Soto Reyes, presidente del Congreso, deja constancia del voto a favor de los congresistas Cavero Alva, Camones Soriano, Jáuregui Martínez de Aguayo y Ventura Ángel."
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/resultados.csv
> +abstenciones,12
```suggestion
abstenciones,11
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/resultados.csv
> +sin_responder,4
```suggestion
sin_responder,5
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/resultados_grupo.csv
> +AP,7,2,0,3,0,1,1,0
```suggestion
AP,7,2,0,2,1,1,1,0
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-11-votacion/votaciones.csv
> +AP,"VERGARA MENDOZA, ELVIS HERNÁN",ABSTENCION
```suggestion
AP,"VERGARA MENDOZA, ELVIS HERNÁN",SIN_RESPONDER
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-16-votacion/metadatos.csv
> +asunto,"ADMISIÓN A DEBATE DE LA MOCIÓN DE ORDEN DEL DÍA 9428, QUE PROPONE QUE EL CONGRESO DE LA REPUBLICA ACUERDE QUE LA COMISIÓN DE JUSTICIA Y DERECHOS HUMANOS EN EL PLAZO DE 10 DÍAS HÁBILES REALICE
```suggestion
asunto,"ADMISIÓN A DEBATE DE LA MOCIÓN DE ORDEN DEL DÍA 9428, QUE PROPONE QUE EL CONGRESO DE LA REPÚBLICA ACUERDE QUE LA COMISIÓN DE JUSTICIA Y DERECHOS HUMANOS EN EL PLAZO DE 10 DÍAS HÁBILES REALICE UNA INVESTIGACIÓN CONTRA LOS MIEMBROS DE LA JUNTA NACIONAL DE JUSTICIA POR CAUSA GRAVE, EN LOS TÉRMINOS DEL ARTÍCULO 157 DE LA CONSTITUCIÓN POLÍTICA DEL PERU Y DEL ARTÍCULO 15, IN FINE, DE LA LEY ORGÁNICA DE LA JUNTA NACIONAL DE JUSTICIA"
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T16-16-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
16:16,"El congresista Soto Reyes, presidente del Congreso, deja constancia del voto a favor de los congresistas Chiabra León, Camones Soriano y Salhuana Cavides."
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T17-06-asistencia/notas.csv
> +hora,nota
```suggestion
hora,nota
17:06,"El congresista Alegría García, primer vicepresidente del Congreso, en ejercicio de la Presidencia, deja constancia de la asistencia de los congresistas Jáuregui Martínez de Aguayo, Zea Choquechambi, Sánchez Palomino, Robles Araujo, Quiroz Barboza y Paredes Gonzales."
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T17-09-votacion/metadatos.csv
> +asunto,"ADMISIÓN A DEBATE DE LA MOCIÓN 9648, QUE PROPONE QUE EL CONGRESO DE LA REPUBLICA APRUEBE LA CONFORMACIÓN DE UNA COMISIÓN DE ALTO NIVEL MULTIPARTIDARIA ENCARGADA DE PRESENTAR UNA PROPUESTA DE
```suggestion
asunto,"ADMISIÓN A DEBATE DE LA MOCIÓN 9648, QUE PROPONE QUE EL CONGRESO DE LA REPÚBLICA APRUEBE LA CONFORMACIÓN DE UNA COMISIÓN DE ALTO NIVEL MULTIPARTIDARIA ENCARGADA DE PRESENTAR UNA PROPUESTA DE REFORMA INTEGRAL DEL SISTEMA DE ADMINISTRACIÓN DE JUSTICIA EN EL PERU EN UN PLAZO MÁXIMO DE 45 DÍAS HÁBILES"
```

2024-02-07 22:36 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T17-09-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
17:09,"El congresista Soto Reyes, presidente del Congreso, deja constancia del voto a favor de los congresistas Chiabra León, Alegría García, Zea Choquechambi y Camones Soriano; y del voto en contra de los congresistas Jáuregui Martínez de Aguayo, Paredes Gonzales, Quiroz Barboza y Sánchez Palomino."
```

2024-02-13 15:42 UTC, DiegoAlmenara requested changes
Estimado @jeqo ,

Falta revisar los cambios que hice en **"resultados.csv" y "resultados_grupo.csv" de la carpeta "Votación 16:11"**.

También faltaba corregir el error del congresista Rospigliosi Capurro/Herrera Mamani en las listas, pero ya hice las correcciones debido a que ya tengo habilitada la opción de editar los archivos.

Finalmente, en este pleno falta la carpeta correspondiente a la "Votación 11:43" (página 11 del PDF).

Saludos.
Diego

2024-04-02 20:19 UTC, jeqo commented
@DiegoAlmenara gracias por la revision y disculpa la demora!
He subido los cambios faltantes, por favor revisar nuevamente.

2024-04-03 20:32 UTC, DiegoAlmenara requested changes

2024-04-03 20:32 UTC, DiegoAlmenara commented on data/2021-2026/2023/12/15/2023-12-15T11-43-votacion/notas.csv
> +hora,nota
```suggestion
hora,nota
11:43,"La congresista Amuruz Dulanto, tercera vicepresidenta, en ejercicio de la Presidencia, deja constancia del voto a favor de los congresistas Jáuregui Martínez de Aguayo, Portalatino Ávalos y Picón Quedo."
```

2024-04-03 20:33 UTC, DiegoAlmenara approved these changes

2024-04-03 22:10 UTC, merged